export const brands = {
  admiral: "Admiral",
  amana: "Amana",
  arctic_king: "Arctic King",
  ascoli_america: "Ascoli America",
  avanti: "Avanti",
  bosch: "Bosch",
  cafe: "Cafe",
  comfort_aire: "Comfort Aire",
  conservator: "Conservator",
  crosley: "Crosley",
  cuisinart: "Cuisinart",
  danby: "Danby",
  electrolux: "Electrolux",
  estate: "Estate",
  fischer_and_paykel: "Fisher & Paykel",
  fridgidaire: "Fridgidaire",
  fridgidaire_gallery: "Fridgidaire Gallery",
  frigidaire_professional: "Fridgidaire Professional",
  ge: "GE",
  ge_profile: "GE Profile",
  haier: "Haier",
  hisense: "Hisense",
  hotpoint: "Hotpoint",
  inglis: "Inglis",
  jenn_air: "Jenn-Air",
  kenmore: "Kenmore",
  kitchenaid: "Kitchenaid",
  lg: "LG",
  lg_signature: "LG Signature",
  magic_chef: "Magic Chef",
  maytag: "Maytag",
  midea: "Midea",
  mora: "Mora",
  richmond: "Richmond",
  roper: "Roper",
  samsung: "Samsung",
  speed_queen: "Speed Queen",
  tappan: "Tappan",
  whirlpool: "Whirlpool",
  white_westinghouse: "White-Westinghouse",
};

export const colors = {
  Black: "Black",
  "Black Stainless": "Black Stainless",
  Blue: "Blue",
  Bronze: "Bronze",
  Brown: "Brown",
  Champagne: "Champagne",
  Cream: "Cream",
  Gold: "Gold",
  Green: "Green",
  Grey: "Grey",
  Orange: "Orange",
  Other: "Other",
  "Panel Ready": "Panel Ready",
  Purple: "Purple",
  Red: "Red",
  Silver: "Silver",
  Stainless: "Stainless",
  Teal: "Teal",
  White: "White",
  "White Stainless": "White Stainless",
  Wood: "Wood",
  Yellow: "Yellow",
};

export const machineStyles = {
  fridge: {
    "Top & Bottom": "Top & Bottom",
    "Side by Side": "Side by Side",
    "French Door": "French Door",
    "Bottom Mount": "Bottom Mount",
    Upright: "Upright",
    Chest: "Chest",
  },
  washer: {
    "Top Load": "Top Load",
    "Front Load": "Front Load",
    "All in One": "All in One",
    Dishwasher: "Dishwasher",
  },
  dryer: {
    "Top Load Gas": "Top Load Gas",
    "Front Load Gas": "Front Load Gas",
    "Top Load Electric": "Top Load Electric",
    "Front Load Electric": "Front Load Electric",
    "All in One": "All in One",
  },
  range: {
    Gas: "Gas",
    Coil: "Coil",
    "Glass Top": "Glass Top",
  },
};
