"""added machine status history table to models to track status changes over time

Revision ID: 66d489063b31
Revises: 
Create Date: 2025-11-24 14:00:59.794484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66d489063b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'trashed', 'in_progress', 'exported', 'archived', name='status_enum'), nullable=False),
    sa.Column('prev_status', sa.Enum('completed', 'trashed', 'in_progress', 'exported', 'archived', name='status_enum'), nullable=False),
    sa.Column('changed_on', sa.Date(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    op.drop_table('machine_status_history')
    # ### end Alembic commands ###
