"""added machine status history table to models to track status changes over time

Revision ID: 66d489063b31
Revises: 
Create Date: 2025-11-24 14:00:59.794484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66d489063b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'trashed', 'in_progress', 'exported', 'archived', name='status_enum'), nullable=False),
    sa.Column('prev_status', sa.Enum('completed', 'trashed', 'in_progress', 'exported', 'archived', name='status_enum'), nullable=False),
    sa.Column('changed_on', sa.Date(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('user')
    op.drop_table('machine_techs')
    op.drop_table('note')
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('serial'))

    op.drop_table('machine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type_of', mysql.ENUM('fridge', 'washer', 'dryer', 'range', 'microwave', 'water_heater', 'stackable', 'dishwasher'), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('serial', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('style', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('condition', mysql.ENUM('NEW', 'USED', 'Scratch and Dent'), nullable=False),
    sa.Column('vendor', mysql.ENUM('pasadena', 'baton_rouge', 'alexandria', 'stines_lc', 'stines_jn', 'scrappers', 'unknown'), nullable=True),
    sa.Column('status', mysql.ENUM('completed', 'trashed', 'in_progress', 'exported', 'archived'), nullable=False),
    sa.Column('need_to_inventory', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('started_on', mysql.DATETIME(), nullable=True),
    sa.Column('completed_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trashed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], name='machine_ibfk_2'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='machine_ibfk_1'),
    sa.ForeignKeyConstraint(['trashed_by'], ['user.id'], name='machine_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('serial'), ['serial'], unique=True)

    op.create_table('note',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('machine_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], name=op.f('note_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('note_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('machine_techs',
    sa.Column('machine_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], name=op.f('machine_techs_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('machine_techs_ibfk_2')),
    sa.PrimaryKeyConstraint('machine_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.drop_table('machine_status_history')
    # ### end Alembic commands ###
